---
title: "Acharya Replication"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Our goal is to replicate Tables 1 and 3, and all the figures.

# Load Required Packages

library(ri)
library(RItools)
library(car)
library(xtable)
library(effects)
library(RColorBrewer)
library(gt)
library(knitr)
library(dplyr)
library(data.table)
library(foreign)
library(plyr)
library(reshape)
library(sandwich)
library(maps)
library(stargazer)
library(AER)
library(Formula)
library(lme4)
library(cem)
library(latticeExtra)
library(stringr)
library(broom)

# Need to look further into this to see what it is

source("./dataverse_files/panel-utils.R")

# Load Datasets

nes.comb <- read.csv("./dataverse_files/abs-jop-nes-ind.csv", stringsAsFactors = FALSE)
nes.counties <- read.csv("./dataverse_files/abs-jop-nes-white-countydata.csv", stringsAsFactors = FALSE)
countydata <- read.csv("./dataverse_files/abs-jop-countydata.csv", stringsAsFactors = FALSE)
wh.counties <- read.csv("./dataverse_files/abs-jop-cces-white-countydata.csv", stringsAsFactors = FALSE)
cces.comb <- read.csv("./dataverse_files/abs-jop-cces-ind.csv", stringsAsFactors = FALSE)

```


## Figure 2


```{r, echo = FALSE, include = FALSE}

# Table 1 replication
# The code for table 1 replication can be found in slavery-jop-replication.R:

## slavery-jop-replication.R - code to generate results for slavery paper
## 2016-01-11 - created file that replicates JOP R&R submission

data(state.fips)
state.fips <- unique(state.fips[,c("fips","abb")])
state.fips$abb <- as.character(state.fips$abb)
state.fips <- rbind(state.fips, c(2, "AK"))
state.fips <- rbind(state.fips, c(15, "HI"))
rownames(state.fips) <- state.fips$abb
fips.state <- state.fips
rownames(fips.state) <- fips.state$fips
data(county.fips)
dodgerblue.30 <- rgb(30, 144, 255, 76.5, max =255)
indianred.30 <- rgb(205, 92, 92, 76.5, max =255)
indianred.75 <- rgb(205, 92, 92, 191, max =255)


## http://people.su.se/~ma/clustering.pdf
robust.se <- function(fm, clvar){
    # R-codes (www.r-project.org) for computing
    # clustered-standard errors. Mahmood Arai, Jan 26, 2008.
    # The arguments of the function are:
    # fitted model, cluster1 and cluster2
    # You need to install libraries `sandwich' and `lmtest'
  library(sandwich);library(lmtest);
  x <- eval(fm$call$data, envir = parent.frame())
  if ("polr" %in% class(fm)) {
    require(MASS)
    cluster <- x[rownames(predict(fm, type = "probs")), clvar]
  } else {
    cluster <- x[names(predict(fm)), clvar]
  }
  M <- length(unique(cluster))
  N <- length(cluster)
  K <- dim(vcov(fm))[1]
  dfc <- (M/(M-1))*((N-1)/(N-K))
  uj  <- apply(estfun(fm),2, function(x) tapply(x, cluster, sum));
  vcovCL <- dfc*sandwich(fm, meat=crossprod(uj)/N)
  coeftest(fm, vcovCL)
}

ch.row <- function(name, yesno) {
    c(name, ifelse(yesno, "$\\checkmark$", ""))
}

st.list <- c("AL", "AR", "GA", "FL", "KY", "LA", "MS", "MO", "NC", "SC", "TN", "TX", "VA","WV")
cces.comb$abs.sample <- 1 * (cces.comb$state.abb %in% st.list)
wh.counties$abs.sample <- 1 * (wh.counties$state.abb %in% st.list)
countydata$abs.sample <- 1 * (countydata$state.abb %in% st.list)
wh.counties$tractor.growth <- (wh.counties$tractors40 - wh.counties$tractors30)

cces.comb$inc.cat <- factor(cces.comb$inc.cat, levels = c("<20k", "20-50k", "50-100k", "100-150k", "150k+"))
whites <- cces.comb[which(cces.comb$white == 1),]
blacks <- cces.comb[which(cces.comb$black == 1),]
latinos <- cces.comb[which(cces.comb$latino == 1),]
others <- cces.comb[which(cces.comb$white != 1 & cces.comb$black != 1 & cces.comb$latino != 1),]

dim(cces.comb)
dim(whites)
sum(whites$state.abb %in% st.list)

dim(blacks)
sum(blacks$state.abb %in% st.list)

dim(latinos)
sum(latinos$state.abb %in% st.list)


## Individual-level data
southerners <- subset(cces.comb, abs.sample == 1)
s.whites <- subset(whites, abs.sample == 1)
s.blacks <- subset(blacks, abs.sample == 1)
s.latinos <- subset(latinos, abs.sample == 1)
s.whites$state.abb <- factor(s.whites$state.abb)
s.blacks$state.abb <- factor(s.blacks$state.abb)
s.latinos$state.abb <- factor(s.latinos$state.abb)

## County-level data
south.counties <- subset(wh.counties, abs.sample == 1)
south.counties$state.abb <- factor(south.counties$state.abb)
south.counties <- south.counties[order(as.numeric(south.counties$fips)),]

nrow(s.whites)
sum(countydata$state.abb %in% st.list)
dim(south.counties)

## NES Results

nes.counties$abs.sample <- 1 * (nes.counties$state.abb %in% st.list)
nes.comb$abs.sample <- 1 * (nes.comb$state.abb %in% st.list)
nes.whites <- nes.comb[which(nes.comb$white == 1),]
nes.blacks <- nes.comb[which(nes.comb$black == 1),]

## Individual-level analysis
ns.whites <- subset(nes.whites, abs.sample == 1)
ns.blacks <- subset(nes.blacks, abs.sample == 1)
ns.whites$state.abb <- factor(ns.whites$state.abb)
ns.blacks$state.abb <- factor(ns.blacks$state.abb)

dim(nes.whites)
dim(ns.whites)
dim(nes.blacks)
dim(ns.blacks)
sum(nes.counties$state.abb %in% st.list)


base1860.form <- formula(. ~ pslave1860 + log(coarea00) + latitude + I(latitude^2) + longitude + I(longitude^2)+ rugged  + land.ineq1860 + sfarmprop1860 + log(totpop1860) + log(fvalpac1860) + log(acimp1860) + fbprop1860  + rail1860 + water1860 + state.abb)

ind.form <- formula(. ~ pslave1860   + log(coarea00) + latitude + I(latitude^2) + longitude + I(longitude^2) + rugged + land.ineq1860 + sfarmprop1860 + log(totpop1860) + log(fvalpac1860) + log(acimp1860) + fbprop1860 + rail1860 + water1860 + as.factor(educ) +  inc.cat +religion + female + age + state.abb*as.factor(year))

ind.int.form <- formula(. ~ pslave1860   + log(coarea00) + latitude + I(latitude^2) + longitude + I(longitude^2) + rugged + land.ineq1860 + sfarmprop1860 + log(totpop1860) + log(fvalpac1860) + log(acimp1860) + fbprop1860 + rail1860 + water1860 + as.factor(educ)*pslave1860 + inc.cat*pslave1860 + religion*pslave1860 + female*pslave1860 + age*pslave1860  + state.abb*as.factor(year))

context.form <- formula(. ~ pslave1860   + log(coarea00) + latitude + I(latitude^2) + longitude + I(longitude^2) + rugged + land.ineq1860 + sfarmprop1860 + log(totpop1860) + log(fvalpac1860) + log(acimp1860) + fbprop1860 + rail1860 + water1860 + as.factor(educ) + inc.cat  +religion +female + age + blkprop.z00 + log(medinc.z10) + w.unemp.rate2014 + log(wbincratio2014) + state.abb*as.factor(year))
context.int.form <- formula(. ~ pslave1860   + log(coarea00) + latitude + I(latitude^2) + longitude + I(longitude^2) + rugged + land.ineq1860 + sfarmprop1860 + log(totpop1860) + log(fvalpac1860) + log(acimp1860) + fbprop1860 + rail1860 + water1860 + as.factor(educ) +  inc.cat  +religion +female + age + blkprop.z00*pslave1860 + log(medinc.z10)*pslave1860 + w.unemp.rate2014*pslave1860 + log(wbincratio2014)*pslave1860 + state.abb*as.factor(year))

## have to use Formula package for ivreg calls
base.iv.form <- Formula(. ~ pslave1860 + log(coarea00) + rugged + latitude + I(latitude^2) + longitude + I(longitude^2)  + water1860  + state.abb | cottonsuit + log(coarea00) + rugged  + latitude + I(latitude^2) + longitude + I(longitude^2) + water1860  + state.abb)

base.first.form <- formula(pslave1860 ~ cottonsuit + log(coarea00) + rugged + latitude + I(latitude^2) + longitude + I(longitude^2)  +water1860 + state.abb)

rform.form <- formula(. ~  cottonsuit + log(coarea00) + rugged + latitude + I(latitude^2)+ longitude + I(longitude^2)  + water1860+  state.abb)



#cairo_pdf(filename = "../figs/scatters.pdf", family = "Minion Pro", height = 5.5, width = 6.5, pointsize = 11)
par(mfrow = c(2,2), mar = 0.1 + c(5, 4, 0, 2))
plot(south.counties$pslave, south.counties$dem, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "Proportion Democrat", yaxt = "n", cex = south.counties$sample.size/100)
axis(side = 2, las = 2)
abline(lm(dem ~ pslave1860, data = south.counties, weights = sample.size), lwd = 2, col = "#AA0000")
plot(south.counties$pslave1860, south.counties$affirm, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "Support for Affirmative Action", yaxt = "n", cex = south.counties$sample.size/100)
axis(side = 2, las = 2)
abline(lm(affirm ~ pslave1860, data = south.counties, weights = sample.size), lwd = 2, col = "#AA0000")
plot(south.counties$pslave1860, south.counties$resent, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "Racial Resentment", yaxt = "n", cex = south.counties$sample.size.res/75)
axis(side = 2, las = 2)
abline(lm(resent ~ pslave1860, data = south.counties, weights = sample.size.res), lwd = 2, col = "#AA0000")
with(subset(nes.counties, state.abb %in% st.list), plot(pslave1860, wtherm-btherm, cex = sample.size.bt/40, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "White - Black Thermometer Score", las = 1, xlim = c(0, 0.9)))
abline(lm(I(wtherm-btherm) ~ pslave1860, weights = sample.size.bt, data = subset(nes.counties, state.abb %in% st.list)), lwd = 2, col = "#AA0000")
#dev.off()



```

```{r figure 2, echo = FALSE}

# Figure 2 Plot

#cairo_pdf(filename = "../figs/scatters-alt.pdf", family = "Minion Pro", height = 2.5, width = 7, pointsize = 11)
par(mfrow = c(1,4), mar = 0.1 + c(4, 3, 2, 0.5), cex.main = 1)

plot(south.counties$pslave1860, south.counties$dem, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "", main = "Proportion Democrat", yaxt = "n", cex = south.counties$sample.size/100)
axis(side = 2, las = 2)
abline(lm(dem ~ pslave1860, data = south.counties, weights = sample.size), lwd = 2, col = "#AA0000")
plot(south.counties$pslave1860, south.counties$affirm, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "", main = "Affirmative Action", yaxt = "n", cex = south.counties$sample.size/100)
axis(side = 2, las = 2)
abline(lm(affirm ~ pslave1860, data = south.counties, weights = sample.size), lwd = 2, col = "#AA0000")
plot(south.counties$pslave1860, south.counties$resent, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab="", main = "Racial Resentment", yaxt = "n", cex = south.counties$sample.size.res/75)
axis(side = 2, las = 2)
abline(lm(resent ~ pslave1860, data = south.counties, weights = sample.size.res), lwd = 2, col = "#AA0000")
with(subset(nes.counties, state.abb %in% st.list), plot(pslave1860, wtherm-btherm, cex = sample.size.bt/40, pch = 19, col = "#33333333", xlab = "Proportion Slave, 1860", ylab = "", main = "White - Black Therm. Score", las = 1, xlim = c(0, 0.9)))
abline(lm(I(wtherm-btherm) ~ pslave1860, weights = sample.size.bt, data = subset(nes.counties, state.abb %in% st.list)), lwd = 2, col = "#AA0000")

#dev.off()

```


```{r table1, echo = FALSE, include = FALSE}

## Tables

cnty.res <- lm(dem ~ pslave1860, data = south.counties, weights = sample.size)
summary(cnty.res)

cnty.res.fe <- lm(dem ~ pslave1860 + state.abb, data = south.counties, weights = sample.size)
summary(cnty.res.fe)

cnty.res.full <- lm(update(base1860.form, dem ~ .), data = south.counties, weights = sample.size)
summary(cnty.res.full)

cnty.aff <- lm(affirm ~ pslave1860, data = south.counties, weights = sample.size)
summary(cnty.aff)

cnty.aff.fe <- lm(affirm ~ pslave1860 + state.abb, data = south.counties, weights = sample.size)
summary(cnty.aff.fe)

cnty.aff.full <- lm(update(base1860.form, affirm ~ .), data = south.counties, weights = sample.size)
summary(cnty.aff.full)


cnty.resent <- lm(resent ~ pslave1860, data = south.counties, weights = sample.size.res)
summary(cnty.resent)

cnty.resent.fe <- lm(resent ~ pslave1860 +  state.abb, data = south.counties, weights = sample.size.res)
summary(cnty.resent.fe)

cnty.resent.full <- lm(update(base1860.form, resent ~ .), data = south.counties, weights = sample.size.res)
summary(cnty.resent.full)

## NES Individual Results
therm.mod <- lm(therm.diff ~ pslave1860, data = ns.whites, weights = weight)
therm.mod.rse <- robust.se(therm.mod, clvar = "fips")
therm.mod.rse

therm.mod.fe <- lm(therm.diff ~ pslave1860 + state.abb*as.factor(year), data = ns.whites, weights = weight)
therm.mod.fe.rse <- robust.se(therm.mod.fe, clvar = "fips")
therm.mod.fe.rse

therm.1860 <- lm(update(base1860.form, therm.diff ~ . + state.abb*as.factor(year)), data = ns.whites, weights = weight)
therm.1860.rse <- robust.se(therm.1860, clvar = "fips")
therm.1860.rse

## for comparison with coefficient
0.2*abs(coef(cnty.res.full)["pslave1860"])/sd(south.counties$dem, na.rm = TRUE)
0.2*abs(coef(cnty.aff.full)["pslave1860"])/sd(south.counties$affirm, na.rm = TRUE)
0.2*coef(cnty.resent.full)["pslave1860"]/sd(south.counties$resent, na.rm = TRUE)
0.2*coef(therm.1860)["pslave1860"]/sd(ns.whites$therm.diff, na.rm = TRUE)

## Table 1
tab1 <- stargazer(cnty.res, cnty.res.full, cnty.aff.full, cnty.resent.full,
                  keep = "pslave1860", style = "apsr", omit.stat = c("adj.rsq","ll", "F", "ser"),
                  covariate.labels = c("Prop. Slave, 1860"), dep.var.labels = c("Prop Democrat", "Affirm. Action", "Racial Resentment"), column.sep.width = "0pt", float = FALSE, header = FALSE, add.lines = list(rep("", 4), ch.row("State Fixed Effects", c(FALSE, rep(TRUE,3))), ch.row("1860 Covariates", c(FALSE, rep(TRUE,3))), rep("", 4)), multicolumn = TRUE)
tab1[4] <- "\\\\[-1.8ex] & \\multicolumn{2}{c}{Prop. Democrat} & Affirm. Action & Racial Resentment \\\\ "
tab1 <- gsub("\\{\\*\\}", "\\{\\\\dagger\\}", tab1)
tab1 <- gsub("\\{\\*\\*\\}", "\\{\\*\\}", tab1)
tab1 <- gsub("\\{\\*\\*\\*\\}", "\\{\\*\\*\\}", tab1)
tab1 <- tab1[-(length(tab1)-1)]

```

```{r table 1, echo = FALSE}

# Create the dataframe which we will use to create the table

m <- data.frame(matrix(0, ncol = 6, nrow = 9))

m$X1 <- c("Proproportion slave, 1860", "_", "level", "1860 covariates", "State fixed effects", "State-year fixed effects", "Clustered SEs", "N", "R2")

# Begin filling in the dataframe

# I'm using the tidy function from the broom library to extract 
# the estimate and the std error from the linear model and plug them
# into the dataset

m$X2[1] <- tidy(cnty.res)$estimate[2]
m$X2[2] <- tidy(cnty.res)$std.error[2]

m$X3[1] <- tidy(cnty.res.full)$estimate[2]
m$X3[2] <- tidy(cnty.res.full)$std.error[2]

m$X4[1] <- tidy(cnty.aff.full)$estimate[2]
m$X4[2] <- tidy(cnty.aff.full)$std.error[2]

m$X5[1] <- tidy(cnty.resent.full)$estimate[2]
m$X5[2] <- tidy(cnty.resent.full)$std.error[2]

# I am manually putting in the county value, as it does not depend on the data
# rather where the data was sourced from

m$X2[3] <- "County"
m$X3[3] <- "County"
m$X4[3] <- "County"
m$X5[3] <- "County"

# I can't figure out how to put check marks in, so I'm using X's

m$X3[4] <- "X"
m$X4[4] <- "X"
m$X5[4] <- "X"
m$X3[5] <- "X"
m$X4[5] <- "X"
m$X5[5] <- "X"
m$X6[5] <- "X"
m$X6[6] <- "X"
m$X6[7] <- "X"

# Calculating the n values.

# The n values are the number of rows once NULL values are removed

# For the first column of proportion democrat the model uses the 
# variables # dem and pslave1860:

m$X2[8] <- south.counties %>% 
  
  filter(!is.na(dem)) %>% 
  
  filter(!is.na(pslave1860)) %>% 
  
  filter(!is.na(state.abb)) %>% 
  
  nrow()

# For the second column of the dta is uses the columns dem, pslave1860, and state.abb
# I couldn't quite figure out how this value was calculated

#m$X3[8] <- south.counties %>% 
  
#  filter(!is.na(dem)) %>% 
  
#  filter(!is.na(base1860.form)) %>% 
  
#  nrow()



# At the moment, I still haven't found where the values for the last column came from

m




# gt(data = m, % decimals = 2)>% 
  
  # Add in the title of the table
  
#  tab_header(
#    title = "Table 2. Covariate Balance across treatment conditions"
#  ) %>% 

```



